# IRIS FLOWER CLASSIFICATION

IMPORTING ALL LIBRARIES

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

LOAD IRIS DATA SET

In [3]:
df=pd.read_csv('Iris.csv')
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

PRITING 3 DIFFERENT SUB DATA FRAMES FOR EACH SPECIES

In [4]:
print("Iris flower data of species 'Iris-setosa':")
print(df.loc[df['Species'].values=='Iris-setosa'][:5])

Iris flower data of species 'Iris-setosa':
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [5]:
print("Iris flower data of species 'Iris-versicolor':")
print(df.loc[df['Species'].values=='Iris-versicolor'][:5])

Iris flower data of species 'Iris-versicolor':
    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
50  51            7.0           3.2            4.7           1.4   
51  52            6.4           3.2            4.5           1.5   
52  53            6.9           3.1            4.9           1.5   
53  54            5.5           2.3            4.0           1.3   
54  55            6.5           2.8            4.6           1.5   

            Species  
50  Iris-versicolor  
51  Iris-versicolor  
52  Iris-versicolor  
53  Iris-versicolor  
54  Iris-versicolor  


In [6]:
print("Iris flower data of species 'Iris-virginica':")
print(df.loc[df['Species'].values=='Iris-virginica'][:5])

Iris flower data of species 'Iris-virginica':
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
100  101            6.3           3.3            6.0           2.5   
101  102            5.8           2.7            5.1           1.9   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   

            Species  
100  Iris-virginica  
101  Iris-virginica  
102  Iris-virginica  
103  Iris-virginica  
104  Iris-virginica  


ANALYSING THE STATISTICS OF DATA SET

In [7]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

CHECKING FOR THE MISSING VALUES IN DATA SET

In [8]:
df.isnull().values.any() #GET False if no missing values

False

CHECKING FOR DUPLICATE VALUES IN THE DATA SET

In [9]:
df.isnull().values.any()

False

SEPARTING INPUT AND OUTPUT COLUMNS

In [19]:
data=df.values #data set shape(150,6)
x=data[:,0:5] #x is numpy array of input(all columns except species) bcoz, we find Species from input through the model
y=data[:,5] #y is numpy array of output(Species)
print(x)

[[1 5.1 3.5 1.4 0.2]
 [2 4.9 3.0 1.4 0.2]
 [3 4.7 3.2 1.3 0.2]
 [4 4.6 3.1 1.5 0.2]
 [5 5.0 3.6 1.4 0.2]
 [6 5.4 3.9 1.7 0.4]
 [7 4.6 3.4 1.4 0.3]
 [8 5.0 3.4 1.5 0.2]
 [9 4.4 2.9 1.4 0.2]
 [10 4.9 3.1 1.5 0.1]
 [11 5.4 3.7 1.5 0.2]
 [12 4.8 3.4 1.6 0.2]
 [13 4.8 3.0 1.4 0.1]
 [14 4.3 3.0 1.1 0.1]
 [15 5.8 4.0 1.2 0.2]
 [16 5.7 4.4 1.5 0.4]
 [17 5.4 3.9 1.3 0.4]
 [18 5.1 3.5 1.4 0.3]
 [19 5.7 3.8 1.7 0.3]
 [20 5.1 3.8 1.5 0.3]
 [21 5.4 3.4 1.7 0.2]
 [22 5.1 3.7 1.5 0.4]
 [23 4.6 3.6 1.0 0.2]
 [24 5.1 3.3 1.7 0.5]
 [25 4.8 3.4 1.9 0.2]
 [26 5.0 3.0 1.6 0.2]
 [27 5.0 3.4 1.6 0.4]
 [28 5.2 3.5 1.5 0.2]
 [29 5.2 3.4 1.4 0.2]
 [30 4.7 3.2 1.6 0.2]
 [31 4.8 3.1 1.6 0.2]
 [32 5.4 3.4 1.5 0.4]
 [33 5.2 4.1 1.5 0.1]
 [34 5.5 4.2 1.4 0.2]
 [35 4.9 3.1 1.5 0.1]
 [36 5.0 3.2 1.2 0.2]
 [37 5.5 3.5 1.3 0.2]
 [38 4.9 3.1 1.5 0.1]
 [39 4.4 3.0 1.3 0.2]
 [40 5.1 3.4 1.5 0.2]
 [41 5.0 3.5 1.3 0.3]
 [42 4.5 2.3 1.3 0.3]
 [43 4.4 3.2 1.3 0.2]
 [44 5.0 3.5 1.6 0.6]
 [45 5.1 3.8 1.9 0.4]
 [46 4.8 3.0 1.4 0.

In [20]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

SEPARTING TRAINING AND TESTING DATA 

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print("Input data during training:")
print(x_train) #train data as we x is for input(measurements) and y is for output(species)

Input data during training:
[[144 6.8 3.2 5.9 2.3]
 [112 6.4 2.7 5.3 1.9]
 [90 5.5 2.5 4.0 1.3]
 [44 5.0 3.5 1.6 0.6]
 [78 6.7 3.0 5.0 1.7]
 [91 5.5 2.6 4.4 1.2]
 [54 5.5 2.3 4.0 1.3]
 [17 5.4 3.9 1.3 0.4]
 [115 5.8 2.8 5.1 2.4]
 [60 5.2 2.7 3.9 1.4]
 [147 6.3 2.5 5.0 1.9]
 [72 6.1 2.8 4.0 1.3]
 [128 6.1 3.0 4.9 1.8]
 [89 5.6 3.0 4.1 1.3]
 [32 5.4 3.4 1.5 0.4]
 [25 4.8 3.4 1.9 0.2]
 [42 4.5 2.3 1.3 0.3]
 [53 6.9 3.1 4.9 1.5]
 [143 5.8 2.7 5.1 1.9]
 [82 5.5 2.4 3.7 1.0]
 [127 6.2 2.8 4.8 1.8]
 [51 7.0 3.2 4.7 1.4]
 [18 5.1 3.5 1.4 0.3]
 [30 4.7 3.2 1.6 0.2]
 [66 6.7 3.1 4.4 1.4]
 [136 7.7 3.0 6.1 2.3]
 [94 5.0 2.3 3.3 1.0]
 [41 5.0 3.5 1.3 0.3]
 [45 5.1 3.8 1.9 0.4]
 [5 5.0 3.6 1.4 0.2]
 [75 6.4 2.9 4.3 1.3]
 [145 6.7 3.3 5.7 2.5]
 [19 5.7 3.8 1.7 0.3]
 [95 5.6 2.7 4.2 1.3]
 [6 5.4 3.9 1.7 0.4]
 [46 4.8 3.0 1.4 0.3]
 [22 5.1 3.7 1.5 0.4]
 [114 5.7 2.5 5.0 2.0]
 [26 5.0 3.0 1.6 0.2]
 [24 5.1 3.3 1.7 0.5]
 [47 5.1 3.8 1.6 0.2]
 [71 5.9 3.2 4.8 1.8]
 [68 5.8 2.7 4.1 1.0]
 [62 5.9 3.0 4.2 1

In [29]:
print("Output of x_train during training:")
print(y_train)

Output of x_train during training:
['Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Ir

FITTING THE MODEL USING LOGISTIC REGRESSION

In [33]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train) #input(x) and outpu(y) of training data is fitted into model using logistic regression


C:\Users\Windows\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

MODEL PREDICATION AND FINDING ACCURACY

In [36]:
prediction=model.predict(x_test)  #x_test is numpy for input of testing the data,y_test is output
for i in range(len(prediction)):
  print("Predicted value:",prediction[i],"\tOriginal value:",y_test[i]) #y_test is Species column of test dataset seprated during
                                                                       #model selection

Predicted value: Iris-setosa 	Original value: Iris-setosa
Predicted value: Iris-versicolor 	Original value: Iris-versicolor
Predicted value: Iris-setosa 	Original value: Iris-setosa
Predicted value: Iris-setosa 	Original value: Iris-setosa
Predicted value: Iris-versicolor 	Original value: Iris-versicolor
Predicted value: Iris-virginica 	Original value: Iris-virginica
Predicted value: Iris-setosa 	Original value: Iris-setosa
Predicted value: Iris-virginica 	Original value: Iris-virginica
Predicted value: Iris-versicolor 	Original value: Iris-versicolor
Predicted value: Iris-versicolor 	Original value: Iris-versicolor
Predicted value: Iris-virginica 	Original value: Iris-virginica
Predicted value: Iris-setosa 	Original value: Iris-setosa
Predicted value: Iris-versicolor 	Original value: Iris-versicolor
Predicted value: Iris-setosa 	Original value: Iris-setosa
Predicted value: Iris-setosa 	Original value: Iris-setosa
Predicted value: Iris-virginica 	Original value: Iris-virginica
Predicte

TESTING THE MODEL

In [37]:
from sklearn.metrics import accuracy_score
print("Accuracy of the model:")
print(accuracy_score(y_test,prediction)*100)

Accuracy of the model:
100.0
